spring:
  application:
    name: usermanagement-ms
  webflux:
    base-path: /usermanagement-ms
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/usermanagement?createDatabaseIfNotExist=true
    user: jasho
    password: password

  r2dbc:
    url: r2dbc:mysql://localhost:3306/usermanagement
    username: jasho
    password: password


server:
  port: 8123
